enum AssetFiles {
    /// ASSET_GAMMA_TABLE,
    GammaTable,
    /// ASSET_CREATURECOLORMAP,
    ColorMapCreature,
    /// ASSET_G_CREATURECOLORMAP,
    ColorMapGhostCreature,
    /// ASSET_GHOSTCREATURECOLORMAP,
    ColorMapWraith,
    /// ASSET_PICKUPCOLORMAP,
    ColorMapPickUp,
    /// ASSET_G_PICKUPCOLORMAP,
    ColorMapGhostPickUp,
    /// ASSET_JACOBCOLORMAP,
    ColorMapJacob,
    /// ASSET_G_LEVEL_COLORMAP,
    ColorMapGhostLevel,
    /// ASSET_PLAYERHANDSCOLORMAP,
    ColorMapPlayerHands,
    /// ASSET_G_PLAYERHANDSCOLORMAP,
    ColorMapGhostPlayerHands,
    /// ASSET_AQUAGORE,
    ModelAquagore,
    /// ASSET_BROODMAW,
    ModelBroodmaw,
    /// ASSET_CRYPTCRAWLER,
    ModelCryptcrawler,
    /// ASSET_FIREDEACON,
    ModelFiredeacon,
    /// ASSET_HUNTER,
    ModelHunter,
    /// ASSET_PSISTALKER,
    ModelPsistalker,
    /// ASSET_STORMFLUKE,
    ModelStormfluke,
    /// ASSET_TENTACLE,
    ModelTentacle,
    /// ASSET_WRAITH,
    ModelWraith,
    /// ASSET_PRIMEENTITY,
    ModelPrimeentity,
    /// ASSET_PLAYERMODEL,
    ModelPlayermodel,
    /// ASSET_VANESSA,
    ModelVanessa,
    /// ASSET_ROCKET,
    ModelRocket,
    /// ASSET_GRENADE,
    ModelGrenade,
    /// ASSET_FXBLAST,
    ModelBlasterShot,
    /// ASSET_AQUAGORE_SHOT,
    ModelAquagoreShot,
    /// ASSET_BROODMAW_SHOT,
    ModelBroodmawShot,
    /// ASSET_CRYPTCRAWLER_SHOT,
    ModelCryptcrawlerShot,
    /// ASSET_FIREDEACON_SHOT,
    ModelFiredeaconShot,
    /// ASSET_GIB_GENERIC_1,
    ModelGibGeneric1,
    /// ASSET_GIB_GENERIC_2,
    ModelGibGeneric2,
    /// ASSET_GIB_GENERIC_3,
    ModelGibGeneric3,
    /// ASSET_BLOOD_GENERIC_1,
    ModelBloodGeneric1,
    /// ASSET_CHARLES,
    ModelCharles,
    /// ASSET_HUMAN_GIB_GENERIC_1,
    ModelHumanGibGenric1,
    /// ASSET_HUMAN_GIB_GENERIC_2,
    ModelHumanGibGenric2,
    /// ASSET_HUMAN_GIB_GENERIC_3,
    ModelHumanGibGenric3,
    /// ASSET_PICKUP_AMMO_PISTOL,
    ModelPickupAmmoPistol,
    /// ASSET_PICKUP_AMMO_DOUBLE_PISTOL,
    ModelPickupAmmoDoublePistol,
    /// ASSET_PICKUP_AMMO_SHOTGUN,
    ModelPickupAmmoShotgun,
    /// ASSET_PICKUP_AMMO_MACHINEGUN,
    ModelPickupAmmoMachineGun,
    /// ASSET_PICKUP_AMMO_SNIPER,
    ModelPickupAmmoSniper,
    /// ASSET_PICKUP_AMMO_GRENADE,
    ModelPickupAmmoGrenade,
    /// ASSET_PICKUP_AMMO_ROCKET,
    ModelPickupAmmoRocket,
    /// ASSET_PICKUP_AMMO_GATLINGGUN,
    ModelPickupAmmoGatlingGun,
    /// ASSET_PICKUP_WEAPON_PISTOL,
    ModelPickupWeaponPistol,
    /// ASSET_PICKUP_WEAPON_DOUBLE_PISTOL,
    ModelPickupWeaponDoublePistol,
    /// ASSET_PICKUP_WEAPON_SHOTGUN,
    ModelPickupWeaponShotgun,
    /// ASSET_PICKUP_WEAPON_MACHINEGUN,
    ModelPickupWeaponMachineGun,
    /// ASSET_PICKUP_WEAPON_SNIPER,
    ModelPickupWeaponSniper,
    /// ASSET_PICKUP_WEAPON_GRENADE,
    ModelPickupWeaponGrenade,
    /// ASSET_PICKUP_WEAPON_GATLINGGUN,
    ModelPickupWeaponGatlingGun,
    /// ASSET_PICKUP_WEAPON_SHOCKWAVE,
    ModelPickupWeaponPulseGun,
    /// ASSET_PICKUP_GHOSTVISION,
    ModelPickupGhostVisionGoggles,
    /// ASSET_PICKUP_FOCITALISMAN,
    ModelPickupTalisman,
    /// ASSET_PICKUP_LETTER,
    ModelPickupLetter,
    /// ASSET_PICKUP_KEY1,
    ModelPickupKey1,
    /// ASSET_PICKUP_FLAKJACKET_25,
    ModelPickupJacketLight,
    /// ASSET_PICKUP_FLAKJACKET_50,
    ModelPickupJacketMedium,
    /// ASSET_PICKUP_FLAKJACKET_100,
    ModelPickupJacketHeavy,
    /// ASSET_LEVEL1_SKY,
    SkyLevel1,
    /// ASSET_LEVEL2_SKY,
    SkyLevel2,
    /// ASSET_LEVEL3_SKY,
    SkyLevel3,
    /// ASSET_LEVEL4_SKY,
    SkyLevel4,
    /// ASSET_LEVEL5_SKY,
    SkyLevel5,
    /// ASSET_LEVEL6_SKY,
    SkyLevel6,
    /// ASSET_LEVEL1_SKY_GHOSTPALETTE,
    SkyColorMapGhostLevel1,
    /// ASSET_LEVEL2_SKY_GHOSTPALETTE,
    SkyColorMapGhostLevel2,
    /// ASSET_LEVEL3_SKY_GHOSTPALETTE,
    SkyColorMapGhostLevel3,
    /// ASSET_LEVEL4_SKY_GHOSTPALETTE,
    SkyColorMapGhostLevel4,
    /// ASSET_LEVEL5_SKY_GHOSTPALETTE,
    SkyColorMapGhostLevel5,
    /// ASSET_LEVEL6_SKY_GHOSTPALETTE,
    SkyColorMapGhostLevel6,
    /// ASSET_JACOB_SKIN_RED,
    JacobSkinRed,
    /// ASSET_JACOB_SKIN_GREEN,
    JacobSkinGreen,
    /// ASSET_JACOB_SKIN_BLUE,
    JacobSkinBlue,
    /// ASSET_JACOB_SKIN_YELLOW,
    JacobSkinYellow,
    /// ASSET_LEVEL1A,
    LevelGeometry1A,
    /// ASSET_LEVEL1A_COLLISION,
    LevelCollision1A,
    /// ASSET_LEVEL1A_WAYPOINTNAV,
    LevelWaypointNav1A,
    /// ASSET_LEVEL1A_COLORMAP,
    LevelColorMap1A,
    /// ASSET_LEVEL1B,
    LevelGeometry1B,
    /// ASSET_LEVEL1B_COLLISION,
    LevelCollision1B,
    /// ASSET_LEVEL1B_WAYPOINTNAV,
    LevelWaypointNav1B,
    /// ASSET_LEVEL1B_COLORMAP,
    LevelColorMap1B,
    /// ASSET_LEVEL2A,
    LevelGeometry2A,
    /// ASSET_LEVEL2A_COLLISION,
    LevelCollision2A,
    /// ASSET_LEVEL2A_WAYPOINTNAV,
    LevelWaypointNav2A,
    /// ASSET_LEVEL2A_COLORMAP,
    LevelColorMap2A,
    /// ASSET_LEVEL2B,
    LevelGeometry2B,
    /// ASSET_LEVEL2B_COLLISION,
    LevelCollision2B,
    /// ASSET_LEVEL2B_WAYPOINTNAV,
    LevelWaypointNav2B,
    /// ASSET_LEVEL2B_COLORMAP,
    LevelColorMap2B,
    /// ASSET_LEVEL3A,
    LevelGeometry3A,
    /// ASSET_LEVEL3A_COLLISION,
    LevelCollision3A,
    /// ASSET_LEVEL3A_WAYPOINTNAV,
    LevelWaypointNav3A,
    /// ASSET_LEVEL3A_COLORMAP,
    LevelColorMap3A,
    /// ASSET_LEVEL3B,
    LevelGeometry3B,
    /// ASSET_LEVEL3B_COLLISION,
    LevelCollision3B,
    /// ASSET_LEVEL3B_WAYPOINTNAV,
    LevelWaypointNav3B,
    /// ASSET_LEVEL3B_COLORMAP,
    LevelColorMap3B,
    /// ASSET_LEVEL4A,
    LevelGeometry4A,
    /// ASSET_LEVEL4A_COLLISION,
    LevelCollision4A,
    /// ASSET_LEVEL4A_WAYPOINTNAV,
    LevelWaypointNav4A,
    /// ASSET_LEVEL4A_COLORMAP,
    LevelColorMap4A,
    /// ASSET_LEVEL4B,
    LevelGeometry4B,
    /// ASSET_LEVEL4B_COLLISION,
    LevelCollision4B,
    /// ASSET_LEVEL4B_WAYPOINTNAV,
    LevelWaypointNav4B,
    /// ASSET_LEVEL4B_COLORMAP,
    LevelColorMap4B,
    /// ASSET_LEVEL5A,
    LevelGeometry5A,
    /// ASSET_LEVEL5A_COLLISION,
    LevelCollision5A,
    /// ASSET_LEVEL5A_WAYPOINTNAV,
    LevelWaypointNav5A,
    /// ASSET_LEVEL5A_COLORMAP,
    LevelColorMap5A,
    /// ASSET_LEVEL5B,
    LevelGeometry5B,
    /// ASSET_LEVEL5B_COLLISION,
    LevelCollision5B,
    /// ASSET_LEVEL5B_WAYPOINTNAV,
    LevelWaypointNav5B,
    /// ASSET_LEVEL5B_COLORMAP,
    LevelColorMap5B,
    /// ASSET_LEVEL6,
    LevelGeometry6,
    /// ASSET_LEVEL6_COLLISION,
    LevelCollision6,
    /// ASSET_LEVEL6_WAYPOINTNAV,
    LevelWaypointNav6,
    /// ASSET_LEVEL6_COLORMAP,
    LevelColorMap6,
    /// ASSET_LEVEL7,
    LevelGeometry7,
    /// ASSET_LEVEL7_COLLISION,
    LevelCollision7,
    /// ASSET_LEVEL7_WAYPOINTNAV,
    LevelWaypointNav7,
    /// ASSET_LEVEL7_COLORMAP,
    LevelColorMap7,
    /// ASSET_LEVEL8,
    LevelGeometry8,
    /// ASSET_LEVEL8_COLLISION,
    LevelCollision8,
    /// ASSET_LEVEL8_WAYPOINTNAV,
    LevelWaypointNav8,
    /// ASSET_LEVEL8_COLORMAP,
    LevelColorMap8,
    /// ASSET_LEVELDM1,
    LevelGeometryDm1,
    /// ASSET_LEVELDM1_COLLISION,
    LevelCollisionDm1,
    /// ASSET_LEVELDM1_COLORMAP,
    LevelColorMapDm1,
    /// ASSET_LEVELDM2,
    LevelGeometryDm2,
    /// ASSET_LEVELDM2_COLLISION,
    LevelCollisionDm2,
    /// ASSET_LEVELDM2_COLORMAP,
    LevelColorMapDm2,
    /// ASSET_LEVELDM3,
    LevelGeometryDm3,
    /// ASSET_LEVELDM3_COLLISION,
    LevelCollisionDm3,
    /// ASSET_LEVELDM3_COLORMAP,
    LevelColorMapDm3,
    /// ASSET_LEVELDM4,
    LevelGeometryDm4,
    /// ASSET_LEVELDM4_COLLISION,
    LevelCollisionDm4,
    /// ASSET_LEVELDM4_COLORMAP,
    LevelColorMapDm4,
    /// ASSET_LEVELMONSTERS,
    LevelGeometryMonsters,
    /// ASSET_LEVELMONSTERS_COLLISION,
    LevelCollisionMonsters,
    /// ASSET_LEVELMONSTERS_WAYPOINTNAV,
    LevelWaypointNavMonsters,
    /// ASSET_LEVELDOORS,
    LevelGeometryDoors,
    /// ASSET_LEVELDOORS_COLLISION,
    LevelCollisionDoors,
    /// ASSET_LEVELDOORS_WAYPOINTNAV,
    LevelWaypointNavDoors,
    /// ASSET_SPRITES,
    Sprites,
    /// ASSET_TEXTURE_INFO,
    InfoTextures,
    /// ASSET_SPRITE_TEXTURE_INFO,
    InfoSpriteTextures,
    /// ASSET_TEXTURES,
    Textures,
    /// ASSET_SPRITE_TEXTURES,
    SpriteTextrues,
    /// ASSET_SOUND_DATA,
    Sounds,
    /// ASSET_STRINGTABLE_ENGLISH_UK,
    StringTableEnglishUk,
    /// ASSET_STRINGTABLE_ENGLISH_US,
    StringTableEnglishUs,
    /// ASSET_STRINGTABLE_FRENCH,
    StringTableFrench,
    /// ASSET_STRINGTABLE_ITALIAN,
    StringTableItalian,
    /// ASSET_STRINGTABLE_GERMAN,
    StringTableGerman,
    /// ASSET_STRINGTABLE_SPANISH
    StringTableSpanish
}

